# Generated by Django 4.0.6 on 2022-07-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marks',
            table='marks',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
