# Generated by Django 4.0.6 on 2022-07-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_marks_table_alter_student_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_name',
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(db_column='student_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateField(db_column='created_on', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_on',
            field=models.DateField(auto_now=True, db_column='updated_on', null=True),
        ),
    ]
