# Generated by Django 4.0.6 on 2022-07-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_remove_marks_student_name_marks_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_column='created_on', null=True),
        ),
    ]
