# Generated by Django 4.0.6 on 2022-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_student_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='created_on', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_column='updated_on', null=True),
        ),
    ]
