# Generated by Django 4.0.6 on 2022-07-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_student_created_on_alter_student_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='created_on',
            field=models.DateField(auto_now_add=True, db_column='created_on'),
        ),
    ]
